format_version : 2


pipelines:
  mediwiki-terraform:
    group: mediawiki
    materials:
      mygit:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/rajnig15/AWS-ELB-Autoscasling.git
        branch: master
    stages:
      - execute: # name of stage
          approval: manual
          jobs:
            TerraformPlan: # name of the job
              tasks:
               - script: |
                     cd terraform
                     terraform init
                     terraform plan
